spring:
  data:
    redis:
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          min-idle: 8
          max-idle: 10
          max-wait: -1ms
  datasource:
    #    指定数据源的类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: tyin
        login-password: 123456
        allow:
        enabled: true
      max-wait: 60000
      max-active: 20
      initial-size: 5
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      filters: stat, wall
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: com.tyin.core.config.mybatis.DatabaseMyBatisLog
logging:
  level:
    com.tyin: debug
    com.tyin.core.config.mybatis: info
